using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace TestesSelectPicker.Models
{
    public class Contrato
    {
        
        public string AnoContrato {get => ExtraiAno();}
        public string Numero { get; set; }
        public string Nome { get; set; }

        private string ExtraiAno()
        {
            var regex = new Regex("/{1}[0-9]{4}");
            Match match = regex.Match(this.Numero);
            if (match.Success)
                return match.ToString().ToString().Replace("/", "");
            return this.Numero;
        }

        public override string ToString()
        {
            return $"{AnoContrato} {Numero} - {Nome}";
        }
    }

    public class BuildContratos
    {

        public List<Contrato> lista { get; set; } = new List<Contrato>();



        public BuildContratos()
        {



            //<option>Selecione um Contrato</option>
            this.lista.Add(new Contrato() { Numero = "T9999999", Nome = "" });
            this.lista.Add(new Contrato() { Numero = "S/C", Nome = "" });
            this.lista.Add(new Contrato() { Numero = "11450/2020", Nome = "3CORP" });
            this.lista.Add(new Contrato() { Numero = "0477/2009", Nome = "3CORP" });
            this.lista.Add(new Contrato() { Numero = "1606/2008", Nome = "3CORP" });
            this.lista.Add(new Contrato() { Numero = "1932/2007", Nome = "3CORP" });
            this.lista.Add(new Contrato() { Numero = "3400/2010", Nome = "3CORP" });
            this.lista.Add(new Contrato() { Numero = "6302/2015", Nome = "3CORP" });
            this.lista.Add(new Contrato() { Numero = "2245/2006", Nome = "4LINUX" });
            this.lista.Add(new Contrato() { Numero = "2428/2010", Nome = "4LINUX" });
            this.lista.Add(new Contrato() { Numero = "2501/2014", Nome = "4LINUX" });
            this.lista.Add(new Contrato() { Numero = "4388/2008", Nome = "4LINUX" });
            this.lista.Add(new Contrato() { Numero = "4760/2009", Nome = "4LINUX" });
            this.lista.Add(new Contrato() { Numero = "5118/2012", Nome = "4LINUX" });
            this.lista.Add(new Contrato() { Numero = "1409/2007", Nome = "7COMM" });
            this.lista.Add(new Contrato() { Numero = "4106/2002", Nome = "7COMM" });
            this.lista.Add(new Contrato() { Numero = "4446/2009", Nome = "7COMM" });
            this.lista.Add(new Contrato() { Numero = "1039/2011", Nome = "7NET" });
            this.lista.Add(new Contrato() { Numero = "0298/2006", Nome = "A. FERREIRA FILHO" });
            this.lista.Add(new Contrato() { Numero = "4375/2008", Nome = "A. FERREIRA FILHO" });
            this.lista.Add(new Contrato() { Numero = "1713/2009", Nome = "A7 TELECOM" });
            this.lista.Add(new Contrato() { Numero = "1970/2009", Nome = "A7 TELECOM" });
            this.lista.Add(new Contrato() { Numero = "2305/2014", Nome = "A7 TELECOM" });
            this.lista.Add(new Contrato() { Numero = "1929/2013", Nome = "ACAO" });
            this.lista.Add(new Contrato() { Numero = "3138/2012", Nome = "ACAO" });
            this.lista.Add(new Contrato() { Numero = "1022/2003", Nome = "ACCESSTAGE" });
            this.lista.Add(new Contrato() { Numero = "13901/2018", Nome = "ACCESSTAGE" });
            this.lista.Add(new Contrato() { Numero = "2299/2013", Nome = "ACCESSTAGE" });
            this.lista.Add(new Contrato() { Numero = "2299/2013", Nome = "ACCESSTAGE" });
            this.lista.Add(new Contrato() { Numero = "4250/2008", Nome = "ACCESSTAGE" });
            this.lista.Add(new Contrato() { Numero = "00129/2017", Nome = "ACESSOLINE" });
            this.lista.Add(new Contrato() { Numero = "0141/2012", Nome = "ACTIVEWEB" });
            this.lista.Add(new Contrato() { Numero = "0679/2010", Nome = "ACTIVEWEB" });
            this.lista.Add(new Contrato() { Numero = "0705/2011", Nome = "ACTIVEWEB" });
            this.lista.Add(new Contrato() { Numero = "0972/2008", Nome = "ACTIVEWEB" });
            this.lista.Add(new Contrato() { Numero = "1099/2013", Nome = "ACTIVEWEB" });
            this.lista.Add(new Contrato() { Numero = "2034/2015", Nome = "ACTIVEWEB" });
            this.lista.Add(new Contrato() { Numero = "6430/2012", Nome = "ADVEN" });
            this.lista.Add(new Contrato() { Numero = "0558/2006", Nome = "AFFAIR" });
            this.lista.Add(new Contrato() { Numero = "2797/2006", Nome = "AFFAIR" });
            this.lista.Add(new Contrato() { Numero = "6382/2014", Nome = "AIDC" });
            this.lista.Add(new Contrato() { Numero = "2654/2010", Nome = "AKIYAMA" });
            this.lista.Add(new Contrato() { Numero = "4342/2010", Nome = "AKIYAMA" });
            this.lista.Add(new Contrato() { Numero = "5348/2015", Nome = "AKIYAMA" });
            this.lista.Add(new Contrato() { Numero = "6612/2012", Nome = "AKIYAMA" });
            this.lista.Add(new Contrato() { Numero = "0001/2010", Nome = "AKIYAMA LTDA." });
            this.lista.Add(new Contrato() { Numero = "0696/2003", Nome = "ALCATEL" });
            this.lista.Add(new Contrato() { Numero = "1245/2003", Nome = "ALCATEL" });
            this.lista.Add(new Contrato() { Numero = "0263/2010", Nome = "ALFAPEX" });
            this.lista.Add(new Contrato() { Numero = "0264/2010", Nome = "ALFAPEX" });
            this.lista.Add(new Contrato() { Numero = "0746/2015", Nome = "ALFAPEX" });
            this.lista.Add(new Contrato() { Numero = "3675/2010", Nome = "ALFAPEX" });
            this.lista.Add(new Contrato() { Numero = "5402/2008", Nome = "ALFAPEX" });
            this.lista.Add(new Contrato() { Numero = "05104/2016", Nome = "ALGAR" });
            this.lista.Add(new Contrato() { Numero = "3717/2009", Nome = "ALGAR" });
            this.lista.Add(new Contrato() { Numero = "6470/2015", Nome = "ALGAR" });
            this.lista.Add(new Contrato() { Numero = "04994/2016", Nome = "ALGAR MULTIMIDIA S.A." });
            this.lista.Add(new Contrato() { Numero = "1983/2007", Nome = "ALINFO" });
            this.lista.Add(new Contrato() { Numero = "0798/2015", Nome = "ALLEN RIO" });
            this.lista.Add(new Contrato() { Numero = "4206/2012", Nome = "ALLEN RIO" });
            this.lista.Add(new Contrato() { Numero = "0757/2011", Nome = "ALLIANZ" });
            this.lista.Add(new Contrato() { Numero = "4066/2012", Nome = "ALLUS" });
            this.lista.Add(new Contrato() { Numero = "7066/2016", Nome = "ALPHA" });
            this.lista.Add(new Contrato() { Numero = "7067/2016", Nome = "ALPHA" });
            this.lista.Add(new Contrato() { Numero = "7070/2016", Nome = "ALPHA" });
            this.lista.Add(new Contrato() { Numero = "7071/2016", Nome = "ALPHA" });
            this.lista.Add(new Contrato() { Numero = "9082/2015", Nome = "ALPHA" });
            this.lista.Add(new Contrato() { Numero = "6767/2015", Nome = "ALSAR" });
            this.lista.Add(new Contrato() { Numero = "0926/2004", Nome = "AMAZON" });
            this.lista.Add(new Contrato() { Numero = "1355/2009", Nome = "AMC INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "1356/2009", Nome = "AMC INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "1762/2008", Nome = "AMC INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "12568/2015", Nome = "AMERICA NET" });
            this.lista.Add(new Contrato() { Numero = "2529/2014", Nome = "AMERICA NET" });
            this.lista.Add(new Contrato() { Numero = "3848/2009", Nome = "AMERICA TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "2825/2010", Nome = "ANDERSEN" });
            this.lista.Add(new Contrato() { Numero = "0502/2008", Nome = "APPI TECNOLOGIA SA" });
            this.lista.Add(new Contrato() { Numero = "3497/2011", Nome = "ARQUIMEDES AUTOMACAO E INFORMATICA LTDA" });
            this.lista.Add(new Contrato() { Numero = "1488/2011", Nome = "ASG" });
            this.lista.Add(new Contrato() { Numero = "2812/2000", Nome = "ASG" });
            this.lista.Add(new Contrato() { Numero = "4489/2008", Nome = "ASG" });
            this.lista.Add(new Contrato() { Numero = "4944/2001", Nome = "ASG" });
            this.lista.Add(new Contrato() { Numero = "3937/2008", Nome = "ASSEMP" });
            this.lista.Add(new Contrato() { Numero = "0868/2012", Nome = "ATA COMERCIO E SERVICOS DE INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "3867/2011", Nome = "ATA COMERCIO E SERVICOS DE INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "1947/2008", Nome = "ATOS" });
            this.lista.Add(new Contrato() { Numero = "2025/2008", Nome = "ATOS" });
            this.lista.Add(new Contrato() { Numero = "0308/2010", Nome = "ATP" });
            this.lista.Add(new Contrato() { Numero = "0740/2019", Nome = "ATP" });
            this.lista.Add(new Contrato() { Numero = "1115/2013", Nome = "ATP" });
            this.lista.Add(new Contrato() { Numero = "1142/2013", Nome = "ATP" });
            this.lista.Add(new Contrato() { Numero = "2290/2013", Nome = "ATP" });
            this.lista.Add(new Contrato() { Numero = "4256/2008", Nome = "ATP" });
            this.lista.Add(new Contrato() { Numero = "0344/2006", Nome = "ATTO" });
            this.lista.Add(new Contrato() { Numero = "0421/2006", Nome = "ATTO" });
            this.lista.Add(new Contrato() { Numero = "1600/2006", Nome = "ATTO" });
            this.lista.Add(new Contrato() { Numero = "5270/2011", Nome = "AUSTIN LTDA" });
            this.lista.Add(new Contrato() { Numero = "2504/2006", Nome = "AVD" });
            this.lista.Add(new Contrato() { Numero = "1554/2010", Nome = "B2BR" });
            this.lista.Add(new Contrato() { Numero = "1816/2008", Nome = "B2BR" });
            this.lista.Add(new Contrato() { Numero = "2906/2012", Nome = "B2BR" });
            this.lista.Add(new Contrato() { Numero = "3529/2013", Nome = "B2BR" });
            this.lista.Add(new Contrato() { Numero = "4457/2009", Nome = "B2BR" });
            this.lista.Add(new Contrato() { Numero = "0834/2011", Nome = "B2WEB" });
            this.lista.Add(new Contrato() { Numero = "0197/2010", Nome = "BACONE" });
            this.lista.Add(new Contrato() { Numero = "3844/2014", Nome = "BACONE" });
            this.lista.Add(new Contrato() { Numero = "5716/2015", Nome = "BACONE" });
            this.lista.Add(new Contrato() { Numero = "1802/2001", Nome = "BANCO DO BRASIL" });
            this.lista.Add(new Contrato() { Numero = "2077/2010", Nome = "BEDUSCHI &amp; MARTINS" });
            this.lista.Add(new Contrato() { Numero = "2817/2010", Nome = "BEDUSCHI &amp; MARTINS" });
            this.lista.Add(new Contrato() { Numero = "2944/2009", Nome = "BEDUSCHI &amp; MARTINS" });
            this.lista.Add(new Contrato() { Numero = "2945/2009", Nome = "BEDUSCHI &amp; MARTINS" });
            this.lista.Add(new Contrato() { Numero = "6014/2012", Nome = "BEDUSCHI &amp; MARTINS" });
            this.lista.Add(new Contrato() { Numero = "6731/2015", Nome = "BEDUSCHI &amp; MARTINS" });
            this.lista.Add(new Contrato() { Numero = "2389/2010", Nome = "BELL TEC" });
            this.lista.Add(new Contrato() { Numero = "5953/2011", Nome = "BELLNET" });
            this.lista.Add(new Contrato() { Numero = "7653/2014", Nome = "BENNER TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "0805/2014", Nome = "BINARIO" });
            this.lista.Add(new Contrato() { Numero = "1516/2013", Nome = "BINARIO" });
            this.lista.Add(new Contrato() { Numero = "2054/2009", Nome = "BK" });
            this.lista.Add(new Contrato() { Numero = "1953/2014", Nome = "BM&amp;F BOVESPA" });
            this.lista.Add(new Contrato() { Numero = "2871/2003", Nome = "BMC" });
            this.lista.Add(new Contrato() { Numero = "0640/2010", Nome = "BMTECH" });
            this.lista.Add(new Contrato() { Numero = "0036/2014", Nome = "BNCOM" });
            this.lista.Add(new Contrato() { Numero = "0050/2014", Nome = "BORLAND" });
            this.lista.Add(new Contrato() { Numero = "0265/2011", Nome = "BORLAND" });
            this.lista.Add(new Contrato() { Numero = "0745/2007", Nome = "BOVESPA" });
            this.lista.Add(new Contrato() { Numero = "1327/2009", Nome = "BOVESPA" });
            this.lista.Add(new Contrato() { Numero = "1276/2010", Nome = "BR" });
            this.lista.Add(new Contrato() { Numero = "4777/2009", Nome = "BR" });
            this.lista.Add(new Contrato() { Numero = "0641/2005", Nome = "BRADESCO" });
            this.lista.Add(new Contrato() { Numero = "0173/2009", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "0185/2009", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "0187/2009", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "14084/2017", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "14086/2017", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "2574/2010", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "4712/2008", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "4715/2008", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "4716/2008", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "5607/2008", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "5608/2008", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "5611/2008", Nome = "BRASIL TELECOM" });
            this.lista.Add(new Contrato() { Numero = "0270/2010", Nome = "BRICON" });
            this.lista.Add(new Contrato() { Numero = "6167/2012", Nome = "BRQ" });
            this.lista.Add(new Contrato() { Numero = "1545/2014", Nome = "BRY TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "3568/2009", Nome = "BRY TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "5160/2011", Nome = "BRY TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "5751/2011", Nome = "BRY TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "0217/2007", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "0359/2004", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "0409/2007", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "0410/2007", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "0796/2004", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "0925/2004", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "1051/2005", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "1115/2006", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "2617/2004", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "2634/2007", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "4699/2008", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "4773/2008", Nome = "BSI" });
            this.lista.Add(new Contrato() { Numero = "0185/2013", Nome = "BT" });
            this.lista.Add(new Contrato() { Numero = "09766/2015", Nome = "BT" });
            this.lista.Add(new Contrato() { Numero = "09489/2018", Nome = "BT BRASIL" });
            this.lista.Add(new Contrato() { Numero = "0236/2009", Nome = "BT BRASIL TELECOMUNICACOES LTDA." });
            this.lista.Add(new Contrato() { Numero = "0310/2010", Nome = "BT BRASIL TELECOMUNICACOES LTDA." });
            this.lista.Add(new Contrato() { Numero = "0640/2005", Nome = "BT BRASIL TELECOMUNICACOES LTDA." });
            this.lista.Add(new Contrato() { Numero = "1323/2006", Nome = "BT BRASIL TELECOMUNICACOES LTDA." });
            this.lista.Add(new Contrato() { Numero = "2651/2010", Nome = "BT BRASIL TELECOMUNICACOES LTDA." });
            this.lista.Add(new Contrato() { Numero = "0031/2011", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "0287/2015", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "0348/2013", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "2088/2013", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "2453/2009", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "2724/2009", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "3663/2011", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "3767/2002", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "4086/2008", Nome = "BULL" });
            this.lista.Add(new Contrato() { Numero = "2391/2000", Nome = "C &amp; M" });
            this.lista.Add(new Contrato() { Numero = "0000/2011", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "1191/2007", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "1614/2011", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "2861/2005", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "3987/2013", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "4008/2013", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "4043/2009", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "5631/2011", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "9999/2011", Nome = "CA" });
            this.lista.Add(new Contrato() { Numero = "1940/2006", Nome = "CACTUS" });
            this.lista.Add(new Contrato() { Numero = "5237/2015", Nome = "CAIXA SEGURADORA S/A" });
            this.lista.Add(new Contrato() { Numero = "2482/2006", Nome = "CALL TECNOLOGIA" });
            this.lista.Add(new Contrato() { Numero = "4237/2009", Nome = "CAMPANA &amp; ZAGO" });
            this.lista.Add(new Contrato() { Numero = "4238/2009", Nome = "CAMPANA &amp; ZAGO" });
            this.lista.Add(new Contrato() { Numero = "4239/2009", Nome = "CAMPANA &amp; ZAGO" });
            this.lista.Add(new Contrato() { Numero = "4241/2009", Nome = "CAMPANA &amp; ZAGO" });
            this.lista.Add(new Contrato() { Numero = "4242/2009", Nome = "CAMPANA &amp; ZAGO" });
            this.lista.Add(new Contrato() { Numero = "4243/2009", Nome = "CAMPANA &amp; ZAGO" });
            this.lista.Add(new Contrato() { Numero = "0071/2008", Nome = "CARLOS SANTOS" });
            this.lista.Add(new Contrato() { Numero = "2035/2008", Nome = "CARLOS SANTOS" });
            this.lista.Add(new Contrato() { Numero = "2452/2005", Nome = "CARLOS SANTOS" });
            this.lista.Add(new Contrato() { Numero = "2684/2007", Nome = "CARLOS SANTOS" });
            this.lista.Add(new Contrato() { Numero = "0256/2015", Nome = "CDIS" });
            this.lista.Add(new Contrato() { Numero = "1263/2011", Nome = "CDIS" });
            this.lista.Add(new Contrato() { Numero = "2534/2014", Nome = "CDIS" });
            this.lista.Add(new Contrato() { Numero = "0198/2014", Nome = "CEMIG TELECOM" });
            this.lista.Add(new Contrato() { Numero = "04247/2016", Nome = "CEMIG TELECOM" });
            this.lista.Add(new Contrato() { Numero = "2502/2014", Nome = "CEMIG TELECOM" });
            this.lista.Add(new Contrato() { Numero = "2503/2014", Nome = "CEMIG TELECOM" });
            this.lista.Add(new Contrato() { Numero = "04972/2016", Nome = "CEMIG TELECOMUNICACOES S.A" });
            this.lista.Add(new Contrato() { Numero = "0901/2009", Nome = "CENTRO DE TECNOLOGIA DE SOFTWARE LTDA" });
            this.lista.Add(new Contrato() { Numero = "12565/2015", Nome = "CENTURYLINK" });
            this.lista.Add(new Contrato() { Numero = "0446/2005", Nome = "CESAR REIS OFFICE" });
            this.lista.Add(new Contrato() { Numero = "5917/2012", Nome = "CGMS INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "3606/2009", Nome = "CI&amp;T SOFTWARE" });
            this.lista.Add(new Contrato() { Numero = "0445/2008", Nome = "CIMCORP" });
            this.lista.Add(new Contrato() { Numero = "1490/2005", Nome = "CIMCORP" });
            this.lista.Add(new Contrato() { Numero = "1624/2006", Nome = "CIMCORP" });
            this.lista.Add(new Contrato() { Numero = "3693/2009", Nome = "CIMCORP" });
            this.lista.Add(new Contrato() { Numero = "1012/2015", Nome = "CIVIAM" });
            this.lista.Add(new Contrato() { Numero = "0046/2011", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "0208/2009", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "02248/2016", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "0395/2008", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "10409/2017", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "11464/2020", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "11512/2020", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "12760/2019", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "1773/2008", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "1987/2009", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "3322/2010", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "8706/2016", Nome = "CLARO" });
            this.lista.Add(new Contrato() { Numero = "02372/2021", Nome = "CLARO S.A" });
            this.lista.Add(new Contrato() { Numero = "16725/2020", Nome = "CLARO S.A" });
            this.lista.Add(new Contrato() { Numero = "0050/2006", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "0758/2012", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "08299/2019", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "0952/2011", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "2099/2009", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "2344/2007", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "3817/2014", Nome = "CMA" });
            this.lista.Add(new Contrato() { Numero = "1481/2012", Nome = "CMSD" });
            this.lista.Add(new Contrato() { Numero = "3967/2013", Nome = "CMSD" });
            this.lista.Add(new Contrato() { Numero = "0601/2004", Nome = "COBRA" });
            this.lista.Add(new Contrato() { Numero = "2502/2006", Nome = "COLUMBIA" });
            this.lista.Add(new Contrato() { Numero = "4669/2010", Nome = "COLUMBIA" });
            this.lista.Add(new Contrato() { Numero = "0344/2014", Nome = "COMODO BR" });
            this.lista.Add(new Contrato() { Numero = "2301/2014", Nome = "COMODO BR" });
            this.lista.Add(new Contrato() { Numero = "2014/2007", Nome = "COMPEX" });
            this.lista.Add(new Contrato() { Numero = "1816/2010", Nome = "COMSAT" });
            this.lista.Add(new Contrato() { Numero = "2340/2006", Nome = "CONECTA" });
            this.lista.Add(new Contrato() { Numero = "0057/2011", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "1254/2005", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "1279/2005", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "1682/2005", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "3461/2010", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "4024/2010", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "4443/2018", Nome = "CONNECTCOM" });
            this.lista.Add(new Contrato() { Numero = "5929/2012", Nome = "CONSORCIO BRQ/CAST/BSI" });
            this.lista.Add(new Contrato() { Numero = "6428/2012", Nome = "CONSORCIO BRQ/CAST/BSI" });
            this.lista.Add(new Contrato() { Numero = "07559/2015", Nome = "CONSORCIO CAIXA GILOG" });
            this.lista.Add(new Contrato() { Numero = "5414/2012", Nome = "CONSORCIO CCA 2012" });
            this.lista.Add(new Contrato() { Numero = "4616/2010", Nome = "CONSORCIO CPM BRAXIS/VIVERE/CREDITO IMOBILIARIO" });
            this.lista.Add(new Contrato() { Numero = "3122/2013", Nome = "CONSORCIO CTMARG" });
            this.lista.Add(new Contrato() { Numero = "1440/2008", Nome = "CONSORCIO CTMON" });
            this.lista.Add(new Contrato() { Numero = "3727/2013", Nome = "CONSORCIO CTMONSI" });
            this.lista.Add(new Contrato() { Numero = "1497/2013", Nome = "CONSORCIO DBA/WEB" });
            this.lista.Add(new Contrato() { Numero = "1106/2013", Nome = "CONSORCIO DE DADOS CAIXA PE179-2012" });
            this.lista.Add(new Contrato() { Numero = "1107/2013", Nome = "CONSORCIO DE DADOS CAIXA PE179-2012" });
            this.lista.Add(new Contrato() { Numero = "1108/2013", Nome = "CONSORCIO DE DADOS CAIXA PE179-2012" });
            this.lista.Add(new Contrato() { Numero = "1109/2013", Nome = "CONSORCIO DE DADOS CAIXA PE179-2012" });
            this.lista.Add(new Contrato() { Numero = "2824/2010", Nome = "CONSORCIO EXPRESSO LIVRE" });
            this.lista.Add(new Contrato() { Numero = "0312/2010", Nome = "CONSORCIO INDRA CARTOES" });
            this.lista.Add(new Contrato() { Numero = "3782/2012", Nome = "CONSORCIO INDRA POLITEC 74" });
            this.lista.Add(new Contrato() { Numero = "0848/2010", Nome = "CONSORCIO MOBILIDADE" });
            this.lista.Add(new Contrato() { Numero = "1939/2008", Nome = "CONSORCIO PSC/OSI" });
            this.lista.Add(new Contrato() { Numero = "3944/2009", Nome = "CONSORCIO PSC/OSI" });
            this.lista.Add(new Contrato() { Numero = "0209/2013", Nome = "CONSORCIO REDE DE ACESSO PE 181/7066-2012 GILOG/BR" });
            this.lista.Add(new Contrato() { Numero = "0210/2013", Nome = "CONSORCIO REDE DE ACESSO PE 181/7066-2012 GILOG/BR" });
            this.lista.Add(new Contrato() { Numero = "0211/2013", Nome = "CONSORCIO REDE DE ACESSO PE 181/7066-2012 GILOG/BR" });
            this.lista.Add(new Contrato() { Numero = "0212/2013", Nome = "CONSORCIO REDE DE ACESSO PE 181/7066-2012 GILOG/BR" });
            this.lista.Add(new Contrato() { Numero = "6529/2012", Nome = "CONSORCIO REDE DE ACESSO PE 182/7066-2012" });
            this.lista.Add(new Contrato() { Numero = "6546/2012", Nome = "CONSORCIO REDE DE ACESSO PE 182/7066-2012" });
            this.lista.Add(new Contrato() { Numero = "6547/2012", Nome = "CONSORCIO REDE DE ACESSO PE 182/7066-2012" });
            this.lista.Add(new Contrato() { Numero = "6041/2012", Nome = "CONSORCIO SDH PE164" });
            this.lista.Add(new Contrato() { Numero = "4423/2012", Nome = "CONSORCIO SPREAD/TTY2000/CAIXA-PE087" });
            this.lista.Add(new Contrato() { Numero = "3781/2009", Nome = "CONVERGENCIA" });
            this.lista.Add(new Contrato() { Numero = "3782/2009", Nome = "CONVERGENCIA" });
            this.lista.Add(new Contrato() { Numero = "1714/2003", Nome = "CORPVS" });
            this.lista.Add(new Contrato() { Numero = "0157/2007", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "0337/2013", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "0345/2013", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "0656/2014", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "0757/2003", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "0960/2014", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1049/2013", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1075/2007", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1231/2013", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1649/2012", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1680/2014", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1682/2014", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "1701/2006", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "2181/2011", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "2220/2014", Nome = "CPM BRAXIS" });
            this.lista.Add(new Contrato() { Numero = "03961/2012", Nome = "CPQD" });
            this.lista.Add(new Contrato() { Numero = "3961/2012", Nome = "CPQD" });
            this.lista.Add(new Contrato() { Numero = "5491/2008", Nome = "CPQD" });
            this.lista.Add(new Contrato() { Numero = "6899/2014", Nome = "CPQD" });
            this.lista.Add(new Contrato() { Numero = "7583/2017", Nome = "CPqD" });
            this.lista.Add(new Contrato() { Numero = "7693/2019", Nome = "CPqD" });
            this.lista.Add(new Contrato() { Numero = "8931/2018", Nome = "CPqD" });
            this.lista.Add(new Contrato() { Numero = "1478/2011", Nome = "CPQI" });
            this.lista.Add(new Contrato() { Numero = "0454/2010", Nome = "CRIAR" });
            this.lista.Add(new Contrato() { Numero = "9093/2015", Nome = "CRIATIVA" });
            this.lista.Add(new Contrato() { Numero = "0456/2007", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "0521/2015", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "0755/2005", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "1044/2007", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "1661/2012", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "2814/2010", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "2816/2010", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "2818/2010", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "2880/2009", Nome = "CSC" });
            this.lista.Add(new Contrato() { Numero = "4835/2011", Nome = "CTIS" });
            this.lista.Add(new Contrato() { Numero = "5104/2011", Nome = "CTIS" });
            this.lista.Add(new Contrato() { Numero = "5604/2012", Nome = "CTIS" });
            this.lista.Add(new Contrato() { Numero = "08629/2017", Nome = "CTIS" });
            this.lista.Add(new Contrato() { Numero = "2313/2009", Nome = "CYBENERT INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "0281/2014", Nome = "CZAR" });
            this.lista.Add(new Contrato() { Numero = "5222/2011", Nome = "CZAR" });
            this.lista.Add(new Contrato() { Numero = "1588/2009", Nome = "D.A" });
            this.lista.Add(new Contrato() { Numero = "1588/2009", Nome = "D.A" });
            this.lista.Add(new Contrato() { Numero = "1588/2009", Nome = "D.A" });
            this.lista.Add(new Contrato() { Numero = "1588/2009", Nome = "D.A" });
            this.lista.Add(new Contrato() { Numero = "2888/2010", Nome = "D.A" });
            this.lista.Add(new Contrato() { Numero = "5265/2012", Nome = "D.O. BRASIL" });
            this.lista.Add(new Contrato() { Numero = "5574/2008", Nome = "DAL BOSCO &amp; KAMIMURA" });
            this.lista.Add(new Contrato() { Numero = "0039/2004", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "02250/2016", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "0409/2012", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "0562/2011", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "0692/2013", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "1246/2003", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "1700/2006", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "1827/2006", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "1838/2007", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "1957/2007", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "5254/2015", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "5696/2012", Nome = "DAMOVO" });
            this.lista.Add(new Contrato() { Numero = "0338/2013", Nome = "DATADIVI" });
            this.lista.Add(new Contrato() { Numero = "1231/2014", Nome = "DATADIVI" });
            this.lista.Add(new Contrato() { Numero = "1240/2013", Nome = "DATADIVI" });
            this.lista.Add(new Contrato() { Numero = "5498/2014", Nome = "DATADIVI" });
            this.lista.Add(new Contrato() { Numero = "5697/2012", Nome = "DATAINFO" });
            this.lista.Add(new Contrato() { Numero = "0296/2007", Nome = "DATALINK" });
            this.lista.Add(new Contrato() { Numero = "1289/2007", Nome = "DATALINK" });
            this.lista.Add(new Contrato() { Numero = "2751/2009", Nome = "DATALINK" });
            this.lista.Add(new Contrato() { Numero = "1200/2013", Nome = "DATAMEC" });
            this.lista.Add(new Contrato() { Numero = "0753/2009", Nome = "DATAPOINTER" });
            this.lista.Add(new Contrato() { Numero = "1821/2007", Nome = "DATAPOINTER" });
            this.lista.Add(new Contrato() { Numero = "4933/2011", Nome = "DATAPOINTER" });
            this.lista.Add(new Contrato() { Numero = "2267/2006", Nome = "DATASIST" });
            this.lista.Add(new Contrato() { Numero = "2484/2004", Nome = "DATASIST" });
            this.lista.Add(new Contrato() { Numero = "2781/2014", Nome = "DATAVOX" });
            this.lista.Add(new Contrato() { Numero = "0623/2002", Nome = "DBA" });
            this.lista.Add(new Contrato() { Numero = "1441/2008", Nome = "DBA" });
            this.lista.Add(new Contrato() { Numero = "1912/2008", Nome = "DBA" });
            this.lista.Add(new Contrato() { Numero = "1940/2002", Nome = "DBA" });
            this.lista.Add(new Contrato() { Numero = "4481/2008", Nome = "DBA" });
            this.lista.Add(new Contrato() { Numero = "0377/2012", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "1283/2014", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "1718/2010", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "2815/2010", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "2821/2010", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "4351/2008", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "4699/2010", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "5986/2011", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "7429/2014", Nome = "DECISION" });
            this.lista.Add(new Contrato() { Numero = "0996/2013", Nome = "DEL GRANDE INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "0017/2010", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0441/2010", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0518/2014", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0518/2015", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0624/2012", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0704/2010", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0841/2006", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "0853/2007", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "11638/2017", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "14803/2017", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "2480/2006", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "2481/2006", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "3490/2010", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "3883/2010", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "4196/2009", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "4621/2011", Nome = "DIVIDATA" });
            this.lista.Add(new Contrato() { Numero = "3935/2014", Nome = "DOCS &amp; BYTES" });
            this.lista.Add(new Contrato() { Numero = "0239/2004", Nome = "DTS" });
            this.lista.Add(new Contrato() { Numero = "0829/2006", Nome = "DYNATRACE" });
            this.lista.Add(new Contrato() { Numero = "3071/2012", Nome = "DYNATRACE" });
            this.lista.Add(new Contrato() { Numero = "3085/2005", Nome = "DYNATRACE" });
            this.lista.Add(new Contrato() { Numero = "7304/2014", Nome = "DYNATRACE" });
            this.lista.Add(new Contrato() { Numero = "0534/2014", Nome = "LIFE MONITOR ESTUDOS DE MERCADO LTDA" });
            this.lista.Add(new Contrato() { Numero = "2084/2014", Nome = "ECCOX" });
            this.lista.Add(new Contrato() { Numero = "2204/2005", Nome = "ECCOX" });
            this.lista.Add(new Contrato() { Numero = "3840/2009", Nome = "EITV" });
            this.lista.Add(new Contrato() { Numero = "03119/2021", Nome = "ELEV TECNOLOGIA LTDA" });
            this.lista.Add(new Contrato() { Numero = "10797/2020", Nome = "ELEV TECNOLOGIA LTDA" });
            this.lista.Add(new Contrato() { Numero = "0382/2014", Nome = "EMBARCADERO" });
            this.lista.Add(new Contrato() { Numero = "5444/2012", Nome = "EMBARCADERO" });
            this.lista.Add(new Contrato() { Numero = "0119/2006", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0120/2006", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0121/2006", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0151/2006", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0284/2009", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0312/2012", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0340/2003", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "0394/2003", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "1110/2005", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "1218/2005", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "15795/2020", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "15804/2020", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "1612/2004", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "2030/2004", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "2087/2004", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "3974/2013", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "3975/2013", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "3976/2013", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "4255/2008", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "5466/2012", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "6530/2012", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "6544/2012", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "8657/2020", Nome = "EMBRATEL" });
            this.lista.Add(new Contrato() { Numero = "2503/2006", Nome = "EMC" });
            this.lista.Add(new Contrato() { Numero = "4700/2010", Nome = "EMC" });
            this.lista.Add(new Contrato() { Numero = "6896/2014", Nome = "EMC" });
            this.lista.Add(new Contrato() { Numero = "0023/2007", Nome = "ENTEL" });
            this.lista.Add(new Contrato() { Numero = "2517/2005", Nome = "ENTEL" });
            this.lista.Add(new Contrato() { Numero = "0909/2010", Nome = "EQUISUL" });
            this.lista.Add(new Contrato() { Numero = "1914/2010", Nome = "EQUISUL" });
            this.lista.Add(new Contrato() { Numero = "0399/2010", Nome = "EQUISYSTEM" });
            this.lista.Add(new Contrato() { Numero = "14265/2018", Nome = "E-SALES" });
            this.lista.Add(new Contrato() { Numero = "2451/2008", Nome = "ESUTA" });
            this.lista.Add(new Contrato() { Numero = "2954/2008", Nome = "ESUTA" });
            this.lista.Add(new Contrato() { Numero = "0118/2009", Nome = "EUROGIRO" });
            this.lista.Add(new Contrato() { Numero = "9999/2010", Nome = "EUROGIRO" });
            this.lista.Add(new Contrato() { Numero = "4094/2010", Nome = "EVERMOBILE" });
            this.lista.Add(new Contrato() { Numero = "2545/2003", Nome = "EVERSYSTEMS" });
            this.lista.Add(new Contrato() { Numero = "2871/2006", Nome = "EXCHANGE" });
            this.lista.Add(new Contrato() { Numero = "1361/2005", Nome = "EXIMIA" });
            this.lista.Add(new Contrato() { Numero = "2924/2004", Nome = "EXIMIA" });
            this.lista.Add(new Contrato() { Numero = "2652/2007", Nome = "EXPERIAN BRASIL LTDA" });
            this.lista.Add(new Contrato() { Numero = "0814/2014", Nome = "F2C" });
            this.lista.Add(new Contrato() { Numero = "1242/2009", Nome = "FABIANA NUNES DE MOURA" });
            this.lista.Add(new Contrato() { Numero = "3765/2010", Nome = "FABIANA NUNES DE MOURA" });
            this.lista.Add(new Contrato() { Numero = "3072/2010", Nome = "FACC" });
            this.lista.Add(new Contrato() { Numero = "3902/2013", Nome = "FACIL" });
            this.lista.Add(new Contrato() { Numero = "6262/2012", Nome = "FACIL" });
            this.lista.Add(new Contrato() { Numero = "1791/2013", Nome = "FACTI" });
            this.lista.Add(new Contrato() { Numero = "1975/2013", Nome = "FAST SECURITY" });
            this.lista.Add(new Contrato() { Numero = "6012/2012", Nome = "FEBEX" });
            this.lista.Add(new Contrato() { Numero = "2559/2010", Nome = "FERTRO" });
            this.lista.Add(new Contrato() { Numero = "0751/2009", Nome = "FINANCEWARE" });
            this.lista.Add(new Contrato() { Numero = "4143/2014", Nome = "FINANCEWARE" });
            this.lista.Add(new Contrato() { Numero = "14216/2018", Nome = "FINNET" });
            this.lista.Add(new Contrato() { Numero = "2297/2013", Nome = "FINNET" });
            this.lista.Add(new Contrato() { Numero = "4238/2008", Nome = "FINNET" });
            this.lista.Add(new Contrato() { Numero = "1468/2014", Nome = "FIRST DECISION" });
            this.lista.Add(new Contrato() { Numero = "2820/2009", Nome = "FIVE ACTS" });
            this.lista.Add(new Contrato() { Numero = "0486/2008", Nome = "FOCO TELECOM &amp; NETWORKING" });
            this.lista.Add(new Contrato() { Numero = "00224/2017", Nome = "FORTEL" });
            this.lista.Add(new Contrato() { Numero = "11457/2020", Nome = "FORTEL" });
            this.lista.Add(new Contrato() { Numero = "2301/2006", Nome = "FOTON" });
            this.lista.Add(new Contrato() { Numero = "6870/2015", Nome = "FOTON" });
            this.lista.Add(new Contrato() { Numero = "5672/2012", Nome = "FQT" });
            this.lista.Add(new Contrato() { Numero = "12154/2020", Nome = "FREE WAY" });
            this.lista.Add(new Contrato() { Numero = "2437/2014", Nome = "FREE WAY" });
            this.lista.Add(new Contrato() { Numero = "2230/2008", Nome = "FUNCATE" });
            this.lista.Add(new Contrato() { Numero = "2915/2006", Nome = "FUNDACAO CASSIMIRO" });
            this.lista.Add(new Contrato() { Numero = "4611/2009", Nome = "G&amp;P" });
            this.lista.Add(new Contrato() { Numero = "4612/2009", Nome = "G&amp;P" });
            this.lista.Add(new Contrato() { Numero = "4613/2009", Nome = "G&amp;P" });
            this.lista.Add(new Contrato() { Numero = "7900/2015", Nome = "G&amp;P" });
            this.lista.Add(new Contrato() { Numero = "0689/2012", Nome = "G4S" });
            this.lista.Add(new Contrato() { Numero = "0192/2014", Nome = "GARTNER" });
            this.lista.Add(new Contrato() { Numero = "0708/2003", Nome = "GARTNER" });
            this.lista.Add(new Contrato() { Numero = "0990/2009", Nome = "GARTNER" });
            this.lista.Add(new Contrato() { Numero = "0000/2011", Nome = "GAS INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "1206/2006", Nome = "GAS INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "1921/2011", Nome = "GAS INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "4340/2008", Nome = "GD BURTI" });
            this.lista.Add(new Contrato() { Numero = "0000/2010", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "1508/2010", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "2609/2005", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "2900/2006", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "3677/2013", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "4356/2012", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "4494/2010", Nome = "GFS" });
            this.lista.Add(new Contrato() { Numero = "1097/2010", Nome = "GLOBALMINDS" });
            this.lista.Add(new Contrato() { Numero = "2556/2010", Nome = "GOLDEN" });
            this.lista.Add(new Contrato() { Numero = "0787/2007", Nome = "GOMAC" });
            this.lista.Add(new Contrato() { Numero = "0788/2007", Nome = "GOMAC" });
            this.lista.Add(new Contrato() { Numero = "2413/2011", Nome = "GOMAQ" });
            this.lista.Add(new Contrato() { Numero = "1251/2009", Nome = "GPS" });
            this.lista.Add(new Contrato() { Numero = "3671/2013", Nome = "GRADDA" });
            this.lista.Add(new Contrato() { Numero = "3411/2010", Nome = "GRECO" });
            this.lista.Add(new Contrato() { Numero = "2597/2010", Nome = "GS TECNOLOGIA E NEGOCIOS" });
            this.lista.Add(new Contrato() { Numero = "5376/2012", Nome = "GS TECNOLOGIA E NEGOCIOS" });
            this.lista.Add(new Contrato() { Numero = "2928/2009", Nome = "GUARAPUAVA" });
            this.lista.Add(new Contrato() { Numero = "3107/2013", Nome = "GVT" });
            this.lista.Add(new Contrato() { Numero = "3108/2013", Nome = "GVT" });
            this.lista.Add(new Contrato() { Numero = "3962/2013", Nome = "GVT" });
            this.lista.Add(new Contrato() { Numero = "3963/2013", Nome = "GVT" });
            this.lista.Add(new Contrato() { Numero = "3964/2013", Nome = "GVT" });
            this.lista.Add(new Contrato() { Numero = "1155/2008", Nome = "HABILTECS" });
            this.lista.Add(new Contrato() { Numero = "2558/2010", Nome = "HABILTECS" });
            this.lista.Add(new Contrato() { Numero = "2562/2010", Nome = "HABILTECS" });
            this.lista.Add(new Contrato() { Numero = "1054/2015", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "2118/2013", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "4766/2012", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "5308/2012", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "5394/2014", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "5953/2014", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "8168/2014", Nome = "HASKY AUTOMACAO E TECNOLOGIA DA INFORMACAO LTDA EP" });
            this.lista.Add(new Contrato() { Numero = "3834/2009", Nome = "HOT SWAP" });
            this.lista.Add(new Contrato() { Numero = "1066/2011", Nome = "HOUTER" });
            this.lista.Add(new Contrato() { Numero = "0010/2009", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "1444/2007", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "1675/2009", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "2525/2014", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "2528/2003", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "2541/2010", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "2724/2003", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "3385/2012", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "3464/2009", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "3759/2013", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "4003/2009", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "5637/2012", Nome = "HP" });
            this.lista.Add(new Contrato() { Numero = "0042/2009", Nome = "HPRINT" });
            this.lista.Add(new Contrato() { Numero = "0356/2007", Nome = "HPRINT" });
            this.lista.Add(new Contrato() { Numero = "4546/2008", Nome = "IBEG INSTITUTO BRASILEIRO DE EDUCACAO E GESTAO" });
            this.lista.Add(new Contrato() { Numero = "0000/2009", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0001/2003", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0074/2010", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0076/2010", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0118/2010", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0337/2003", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0389/2012", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "3084/2005", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "3282/2004", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "3980/2013", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "3988/2013", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "4022/2013", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "4557/2009", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "6300/2012", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "8031/2014", Nome = "IBM" });
            this.lista.Add(new Contrato() { Numero = "0110/2010", Nome = "IBROWSE" });
            this.lista.Add(new Contrato() { Numero = "0156/2010", Nome = "IBROWSE" });
            this.lista.Add(new Contrato() { Numero = "0205/2010", Nome = "IBROWSE" });
            this.lista.Add(new Contrato() { Numero = "0585/2010", Nome = "IBROWSE" });
            this.lista.Add(new Contrato() { Numero = "3693/2011", Nome = "IBROWSE" });
            this.lista.Add(new Contrato() { Numero = "2753/2008", Nome = "IDDEIA" });
            this.lista.Add(new Contrato() { Numero = "5612/2008", Nome = "IDDEIA" });
            this.lista.Add(new Contrato() { Numero = "5613/2008", Nome = "IDDEIA" });
            this.lista.Add(new Contrato() { Numero = "1795/2010", Nome = "ILHA SERVICE" });
            this.lista.Add(new Contrato() { Numero = "4377/2009", Nome = "ILHA SERVICE" });
            this.lista.Add(new Contrato() { Numero = "0190/2006", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "0287/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "0624/2002", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "0741/2002", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "0980/2006", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "1323/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "1443/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "1935/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "1936/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "1941/2002", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "2006/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "2036/2009", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "2160/2013", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "2421/2008", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "3777/2012", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "5224/2012", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "5225/2012", Nome = "INDRA" });
            this.lista.Add(new Contrato() { Numero = "5677/2012", Nome = "INDRA CONSORCIO POLITEC 137" });
            this.lista.Add(new Contrato() { Numero = "3719/2009", Nome = "INDUSTRIA GRAFICA BRASILEIRA LTDA" });
            this.lista.Add(new Contrato() { Numero = "0596/2010", Nome = "INGENICO DOBRASIL LTDA" });
            this.lista.Add(new Contrato() { Numero = "07301/2018", Nome = "INOVAX" });
            this.lista.Add(new Contrato() { Numero = "6555/2012", Nome = "INOVAX" });
            this.lista.Add(new Contrato() { Numero = "0368/2012", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "0530/2011", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "0708/2013", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "0733/2010", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "1216/2010", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "1451/2014", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "3283/2014", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "4276/2010", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "8217/2015", Nome = "INTELBRAS S/A" });
            this.lista.Add(new Contrato() { Numero = "1108/2003", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "12551/2015", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "1271/2002", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "1325/2002", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "1628/2003", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "2110/2007", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "2201/2008", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "2206/2008", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "2207/2008", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "2500/2014", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "4713/2008", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "5038/2012", Nome = "INTELIG" });
            this.lista.Add(new Contrato() { Numero = "1336/2006", Nome = "INTELIREDES" });
            this.lista.Add(new Contrato() { Numero = "1025/2003", Nome = "INTERCHANGE" });
            this.lista.Add(new Contrato() { Numero = "1677/2014", Nome = "INTERSYSTEMS" });
            this.lista.Add(new Contrato() { Numero = "3087/2005", Nome = "INTERSYSTEMS" });
            this.lista.Add(new Contrato() { Numero = "3286/2010", Nome = "INTERSYSTEMS" });
            this.lista.Add(new Contrato() { Numero = "3203/2013", Nome = "ISH" });
            this.lista.Add(new Contrato() { Numero = "7474/2014", Nome = "ISO EXPERT" });
            this.lista.Add(new Contrato() { Numero = "1416/2012", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "2179/2014", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "2835/2013", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "3803/2010", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "4114/2009", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "5675/2011", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "6175/2012", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "7271/2014", Nome = "IT2B" });
            this.lista.Add(new Contrato() { Numero = "0378/2010", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "0592/2005", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "0856/2007", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "1201/2007", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "1390/2007", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "1535/2009", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "1535/2009", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "1535/2009", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "2053/2009", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "2844/2005", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "3005/2008", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "4477/2009", Nome = "ITAUTEC" });
            this.lista.Add(new Contrato() { Numero = "0131/2014", Nome = "JC TELECOM" });
            this.lista.Add(new Contrato() { Numero = "1515/2009", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1515/2009", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1515/2009", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1515/2009", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1515/2009", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1515/2009", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1575/2006", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "3838/2014", Nome = "JELTE" });
            this.lista.Add(new Contrato() { Numero = "1184/2014", Nome = "L &amp; B SOLUCOES EM TI" });
            this.lista.Add(new Contrato() { Numero = "1372/2007", Nome = "LABORE" });
            this.lista.Add(new Contrato() { Numero = "3088/2014", Nome = "LAM TI" });
            this.lista.Add(new Contrato() { Numero = "3402/2010", Nome = "LANPORT" });
            this.lista.Add(new Contrato() { Numero = "3403/2010", Nome = "LANPORT" });
            this.lista.Add(new Contrato() { Numero = "5909/2014", Nome = "LAW PS" });
            this.lista.Add(new Contrato() { Numero = "6227/2015", Nome = "LBS LOCAL" });
            this.lista.Add(new Contrato() { Numero = "0232/2007", Nome = "LENOVO" });
            this.lista.Add(new Contrato() { Numero = "2730/2006", Nome = "LENOVO" });
            this.lista.Add(new Contrato() { Numero = "4372/2015", Nome = "LENOVO" });
            this.lista.Add(new Contrato() { Numero = "6785/2014", Nome = "LENOVO" });
            this.lista.Add(new Contrato() { Numero = "0628/2010", Nome = "LEUCOTRON" });
            this.lista.Add(new Contrato() { Numero = "0971/2004", Nome = "LEUCOTRON" });
            this.lista.Add(new Contrato() { Numero = "1549/2007", Nome = "LEUCOTRON" });
            this.lista.Add(new Contrato() { Numero = "1582/2008", Nome = "LEUCOTRON" });
            this.lista.Add(new Contrato() { Numero = "1607/2008", Nome = "LEUCOTRON" });
            this.lista.Add(new Contrato() { Numero = "2843/2005", Nome = "LEUCOTRON" });
            this.lista.Add(new Contrato() { Numero = "5997/2012", Nome = "LEVEL 3" });
            this.lista.Add(new Contrato() { Numero = "4365/2008", Nome = "LIBERIUN" });
            this.lista.Add(new Contrato() { Numero = "2813/2010", Nome = "LINK INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "2820/2010", Nome = "LINK INFORMATICA" });
            this.lista.Add(new Contrato() { Numero = "0016/2007", Nome = "LITORAL NORTE" });
            this.lista.Add(new Contrato() { Numero = "0512/2007", Nome = "LITORAL NORTE" });
            this.lista.Add(new Contrato() { Numero = "0283/2013", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "1080/2010", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "1726/2007", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "1743/2005", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "2031/2014", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "2219/2010", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "3836/2009", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "4338/2010", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "5637/2008", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "6612/2014", Nome = "MAISDOISX" });
            this.lista.Add(new Contrato() { Numero = "0543/2012", Nome = "MAPS" });
            this.lista.Add(new Contrato() { Numero = "1540/2006", Nome = "MAPS" });
            this.lista.Add(new Contrato() { Numero = "2438/2010", Nome = "MAPS" });
            this.lista.Add(new Contrato() { Numero = "7124/2014", Nome = "MAPS" });
            this.lista.Add(new Contrato() { Numero = "2557/2010", Nome = "MARTA BATISTA" });
            this.lista.Add(new Contrato() { Numero = "7310/2014", Nome = "MCR" });
            this.lista.Add(new Contrato() { Numero = "1281/2011", Nome = "MEDIDATA" });
            this.lista.Add(new Contrato() { Numero = "2069/2006", Nome = "MEDIDATA" });
            this.lista.Add(new Contrato() { Numero = "1026/2003", Nome = "MERCADOR" });
            this.lista.Add(new Contrato() { Numero = "1438/2008", Nome = "META" });
            this.lista.Add(new Contrato() { Numero = "2680/2003", Nome = "METRORED" });
            this.lista.Add(new Contrato() { Numero = "1469/2010", Nome = "MI MONTREAL" });
            this.lista.Add(new Contrato() { Numero = "1494/2008", Nome = "MICROBANK" });
            this.lista.Add(new Contrato() { Numero = "1494/2008", Nome = "MICROBANK" });
            this.lista.Add(new Contrato() { Numero = "1494/2008", Nome = "MICROBANK" });
            this.lista.Add(new Contrato() { Numero = "1494/2008", Nome = "MICROBANK" });
            this.lista.Add(new Contrato() { Numero = "1494/2008", Nome = "MICROBANK" });
            this.lista.Add(new Contrato() { Numero = "3251/2013", Nome = "MICROBUSINESS" });
            this.lista.Add(new Contrato() { Numero = "1749/2006", Nome = "MICROCENTER" });
            this.lista.Add(new Contrato() { Numero = "5129/2018", Nome = "MICROLINEA" });
            this.lista.Add(new Contrato() { Numero = "0248/2004", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "1210/2010", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "2211/2005", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "2501/2006", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "2819/2010", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "2824/2005", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "2847/2005", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "4350/2008", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "5529/2008", Nome = "MICROLOG" });
            this.lista.Add(new Contrato() { Numero = "4132/2014", Nome = "MICROMIDIA" });
            this.lista.Add(new Contrato() { Numero = "7092/2014", Nome = "MICROMIDIA" });
            this.lista.Add(new Contrato() { Numero = "0810/2009", Nome = "MICROSENS" });
            this.lista.Add(new Contrato() { Numero = "1539/2011", Nome = "MICROSENS" });
            this.lista.Add(new Contrato() { Numero = "3763/2009", Nome = "MICROSENS" });
            this.lista.Add(new Contrato() { Numero = "0655/2006", Nome = "MICROSOFT" });
            this.lista.Add(new Contrato() { Numero = "1405/2008", Nome = "MICROSOFT" });
            this.lista.Add(new Contrato() { Numero = "2850/2006", Nome = "MICROTECNICA" });
            this.lista.Add(new Contrato() { Numero = "00222/2017", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "01044/2016", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "11750/2020", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "11790/2020", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "12290/2020", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "12292/2020", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "15364/2020", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "9072/2015", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "9073/2015", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "9074/2015", Nome = "MOB TELECOM" });
            this.lista.Add(new Contrato() { Numero = "2388/2005", Nome = "MODULO" });
            this.lista.Add(new Contrato() { Numero = "3487/2013", Nome = "MODULO" });
            this.lista.Add(new Contrato() { Numero = "3660/2009", Nome = "MODULO" });
            this.lista.Add(new Contrato() { Numero = "3715/2010", Nome = "MODULO" });
            this.lista.Add(new Contrato() { Numero = "4263/2002", Nome = "MODULO" });
            this.lista.Add(new Contrato() { Numero = "0092/2010", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "0273/2017", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "0338/2014", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "0552/2009", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "0658/2013", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "1426/2014", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3272/2012", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3303/2009", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3352/2014", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3448/2009", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3504/2013", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3680/2015", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "3695/2011", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "5145/2014", Nome = "MTI" });
            this.lista.Add(new Contrato() { Numero = "1037/2010", Nome = "MULTISUPRIMENTOS" });
            this.lista.Add(new Contrato() { Numero = "1590/2009", Nome = "MULTISUPRIMENTOS" });
            this.lista.Add(new Contrato() { Numero = "3237/2009", Nome = "MULTISUPRIMENTOS" });
            this.lista.Add(new Contrato() { Numero = "7448/2014", Nome = "MUNDO TELECOM" });
            this.lista.Add(new Contrato() { Numero = "0356/2013", Nome = "MURAH" });
            this.lista.Add(new Contrato() { Numero = "9286/2015", Nome = "MURAH" });
            this.lista.Add(new Contrato() { Numero = "0037/2005", Nome = "NCT" });
            this.lista.Add(new Contrato() { Numero = "1430/2008", Nome = "NCT" });
            this.lista.Add(new Contrato() { Numero = "2102/2005", Nome = "NCT" });
            this.lista.Add(new Contrato() { Numero = "2448/2006", Nome = "NCT" });
            this.lista.Add(new Contrato() { Numero = "2775/2005", Nome = "NCT" });
            this.lista.Add(new Contrato() { Numero = "2814/2003", Nome = "NEC" });
            this.lista.Add(new Contrato() { Numero = "14076/2018", Nome = "NEOGRID" });
            this.lista.Add(new Contrato() { Numero = "2298/2013", Nome = "NEOGRID" });
            this.lista.Add(new Contrato() { Numero = "4252/2008", Nome = "NEOGRID" });
            this.lista.Add(new Contrato() { Numero = "14738/2017", Nome = "NET EXPRESS BRASIL LTDA" });
            this.lista.Add(new Contrato() { Numero = "0240/2015", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "0715/2009", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "0732/2010", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "0762/2010", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "2252/2011", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "3398/2010", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "3399/2010", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "3460/2013", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "4256/2009", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "4278/2010", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "8071/2014", Nome = "NETEC" });
            this.lista.Add(new Contrato() { Numero = "6878/2015", Nome = "NETSAFE" });
            this.lista.Add(new Contrato() { Numero = "4141/2014", Nome = "NETSUL" });
            this.lista.Add(new Contrato() { Numero = "1531/2014", Nome = "NETWORLD" });
            this.lista.Add(new Contrato() { Numero = "1312/2009", Nome = "NEXTSOURCING" });
            this.lista.Add(new Contrato() { Numero = "1027/2003", Nome = "NEXXERA" });
            this.lista.Add(new Contrato() { Numero = "14218/2018", Nome = "NEXXERA" });
            this.lista.Add(new Contrato() { Numero = "2295/2013", Nome = "NEXXERA" });
            this.lista.Add(new Contrato() { Numero = "4257/2008", Nome = "NEXXERA" });
            this.lista.Add(new Contrato() { Numero = "1370/2004", Nome = "NORDESTE" }); ;

        }



    }

}